FROM node:12-alpine
WORKDIR /app/client
COPY package.json .
COPY package-lock.json .
RUN apk add --no-cache --virtual .gyp \
        python \
        make \
        g++ \
    && npm install \
    && apk del .gyp
COPY . .
CMD ["start"]
ENTRYPOINT ["npm", "run"]